apiVersion: batch/v1
kind: Job
metadata:
  name: presync-announce
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # If you had multiple PreSync hooks, you could order them with waves too:
    # argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: announcer
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "=== PreSync: Starting devops-app deploy at $(date) ===";
              sleep 2;
              echo "=== PreSync: Ready to sync resources (CM -> Deploy -> SVC) ===";
  backoffLimit: 0
