apiVersion: v1
kind: Service
metadata:
  name: devops-app
  labels:
    app: devops-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 80
